# Generated by Grammarinator 19.3

from itertools import chain
from grammarinator.runtime import *

charset_0 = list(chain(range(48, 58)))
charset_1 = list(chain(range(49, 58)))
charset_2 = list(chain(range(97, 123), range(65, 91)))


class inventoryUnlexer(Grammarinator):

    def __init__(self, *, max_depth=float('inf'), weights=None, cooldown=1.0):
        super(inventoryUnlexer, self).__init__()
        self.unlexer = self
        self.max_depth = max_depth
        self.weights = weights or dict()
        self.cooldown = cooldown

    def EOF(self, *args, **kwargs):
        pass

    @depthcontrol
    def DIGIT(self):
        current = self.create_node(UnlexerRule(name='DIGIT'))
        current += self.create_node(UnlexerRule(src=self.char_from_list(charset_0)))
        return current
    DIGIT.min_depth = 0

    @depthcontrol
    def NONZERODIGIT(self):
        current = self.create_node(UnlexerRule(name='NONZERODIGIT'))
        current += self.create_node(UnlexerRule(src=self.char_from_list(charset_1)))
        return current
    NONZERODIGIT.min_depth = 0

    @depthcontrol
    def STRINGLITERAL(self):
        current = self.create_node(UnlexerRule(name='STRINGLITERAL'))
        current += self.create_node(UnlexerRule(src=self.char_from_list(charset_2)))
        return current
    STRINGLITERAL.min_depth = 0

    @depthcontrol
    def BLOCK(self):
        current = self.create_node(UnlexerRule(name='BLOCK'))
        choice = self.choice([0 if [1, 1][i] > self.unlexer.max_depth else w * self.unlexer.weights.get(('alt_0', i), 1) for i, w in enumerate([1, 1])])
        self.unlexer.weights[('alt_0', choice)] = self.unlexer.weights.get(('alt_0', choice), 1) * self.unlexer.cooldown
        if choice == 0:
            current += self.unlexer.STRINGLITERAL()
        elif choice == 1:
            current += self.unlexer.NONZERODIGIT()
        choice = self.choice([0 if [1, 1][i] > self.unlexer.max_depth else w * self.unlexer.weights.get(('alt_3', i), 1) for i, w in enumerate([1, 1])])
        self.unlexer.weights[('alt_3', choice)] = self.unlexer.weights.get(('alt_3', choice), 1) * self.unlexer.cooldown
        if choice == 0:
            current += self.unlexer.STRINGLITERAL()
        elif choice == 1:
            current += self.unlexer.NONZERODIGIT()
        choice = self.choice([0 if [1, 1][i] > self.unlexer.max_depth else w * self.unlexer.weights.get(('alt_6', i), 1) for i, w in enumerate([1, 1])])
        self.unlexer.weights[('alt_6', choice)] = self.unlexer.weights.get(('alt_6', choice), 1) * self.unlexer.cooldown
        if choice == 0:
            current += self.unlexer.STRINGLITERAL()
        elif choice == 1:
            current += self.unlexer.NONZERODIGIT()
        choice = self.choice([0 if [1, 1][i] > self.unlexer.max_depth else w * self.unlexer.weights.get(('alt_9', i), 1) for i, w in enumerate([1, 1])])
        self.unlexer.weights[('alt_9', choice)] = self.unlexer.weights.get(('alt_9', choice), 1) * self.unlexer.cooldown
        if choice == 0:
            current += self.unlexer.STRINGLITERAL()
        elif choice == 1:
            current += self.unlexer.NONZERODIGIT()
        return current
    BLOCK.min_depth = 1

    @depthcontrol
    def PHONEBLOCK(self):
        current = self.create_node(UnlexerRule(name='PHONEBLOCK'))
        current += self.unlexer.NONZERODIGIT()
        current += self.unlexer.NONZERODIGIT()
        current += self.unlexer.NONZERODIGIT()
        return current
    PHONEBLOCK.min_depth = 1

    @depthcontrol
    def DATEBLOCK(self):
        current = self.create_node(UnlexerRule(name='DATEBLOCK'))
        current += self.unlexer.NONZERODIGIT()
        current += self.unlexer.NONZERODIGIT()
        return current
    DATEBLOCK.min_depth = 1

    @depthcontrol
    def OB(self):
        current = self.create_node(UnlexerRule(name='OB'))
        current += self.create_node(UnlexerRule(src='{'))
        return current
    OB.min_depth = 0

    @depthcontrol
    def CB(self):
        current = self.create_node(UnlexerRule(name='CB'))
        current += self.create_node(UnlexerRule(src='}'))
        return current
    CB.min_depth = 0

    @depthcontrol
    def SF(self):
        current = self.create_node(UnlexerRule(name='SF'))
        current += self.create_node(UnlexerRule(src='\\"'))
        return current
    SF.min_depth = 0

    @depthcontrol
    def COMMA(self):
        current = self.create_node(UnlexerRule(name='COMMA'))
        current += self.create_node(UnlexerRule(src=', '))
        return current
    COMMA.min_depth = 0

    @depthcontrol
    def COLLON(self):
        current = self.create_node(UnlexerRule(name='COLLON'))
        current += self.create_node(UnlexerRule(src=': '))
        return current
    COLLON.min_depth = 0

