# Generated by Grammarinator 19.3

from itertools import chain
from grammarinator.runtime import *

import inventoryUnlexer


class inventoryUnparser(Grammarinator):

    def __init__(self, unlexer):
        super(inventoryUnparser, self).__init__()
        self.unlexer = unlexer
    @depthcontrol
    def start(self):
        current = self.create_node(UnparserRule(name='start'))
        current += self.request_line()
        return current
    start.min_depth = 4

    @depthcontrol
    def request_line(self):
        current = self.create_node(UnparserRule(name='request_line'))
        choice = self.choice([0 if [6, 3][i] > self.unlexer.max_depth else w * self.unlexer.weights.get(('alt_17', i), 1) for i, w in enumerate([1, 1])])
        self.unlexer.weights[('alt_17', choice)] = self.unlexer.weights.get(('alt_17', choice), 1) * self.unlexer.cooldown
        if choice == 0:
            current += self.addInventoryItem()
        elif choice == 1:
            current += self.searchInventory()
        return current
    request_line.min_depth = 3

    @depthcontrol
    def integer(self):
        current = self.create_node(UnparserRule(name='integer'))
        choice = self.choice([0 if [1, 1][i] > self.unlexer.max_depth else w * self.unlexer.weights.get(('alt_20', i), 1) for i, w in enumerate([1, 1])])
        self.unlexer.weights[('alt_20', choice)] = self.unlexer.weights.get(('alt_20', choice), 1) * self.unlexer.cooldown
        if choice == 0:
            current += self.unlexer.DIGIT()
        elif choice == 1:
            current += self.unlexer.NONZERODIGIT()
            if self.unlexer.max_depth >= 0:
                for _ in self.one_or_more():
                    current += self.unlexer.DIGIT()

        return current
    integer.min_depth = 1

    @depthcontrol
    def string(self):
        current = self.create_node(UnparserRule(name='string'))
        if self.unlexer.max_depth >= 0:
            for _ in self.one_or_more():
                current += self.unlexer.STRINGLITERAL()

        return current
    string.min_depth = 1

    @depthcontrol
    def guid(self):
        current = self.create_node(UnparserRule(name='guid'))
        current += self.unlexer.BLOCK()
        current += self.unlexer.BLOCK()
        current += self.create_node(UnlexerRule(src='-'))
        current += self.unlexer.BLOCK()
        current += self.create_node(UnlexerRule(src='-'))
        current += self.unlexer.BLOCK()
        current += self.create_node(UnlexerRule(src='-'))
        current += self.unlexer.BLOCK()
        current += self.create_node(UnlexerRule(src='-'))
        current += self.unlexer.BLOCK()
        current += self.unlexer.BLOCK()
        current += self.unlexer.BLOCK()
        return current
    guid.min_depth = 2

    @depthcontrol
    def phone(self):
        current = self.create_node(UnparserRule(name='phone'))
        current += self.unlexer.PHONEBLOCK()
        current += self.create_node(UnlexerRule(src='-'))
        current += self.unlexer.PHONEBLOCK()
        current += self.create_node(UnlexerRule(src='-'))
        current += self.unlexer.PHONEBLOCK()
        current += self.unlexer.NONZERODIGIT()
        return current
    phone.min_depth = 2

    @depthcontrol
    def homepage(self):
        current = self.create_node(UnparserRule(name='homepage'))
        current += self.create_node(UnlexerRule(src='https://www.'))
        if self.unlexer.max_depth >= 0:
            for _ in self.one_or_more():
                current += self.unlexer.STRINGLITERAL()

        current += self.create_node(UnlexerRule(src='.com'))
        return current
    homepage.min_depth = 1

    @depthcontrol
    def date(self):
        current = self.create_node(UnparserRule(name='date'))
        current += self.unlexer.DATEBLOCK()
        current += self.create_node(UnlexerRule(src='/'))
        current += self.unlexer.DATEBLOCK()
        current += self.create_node(UnlexerRule(src='/19'))
        current += self.unlexer.DATEBLOCK()
        return current
    date.min_depth = 2

    @depthcontrol
    def data(self):
        current = self.create_node(UnparserRule(name='data'))
        current += self.create_node(UnlexerRule(src='"'))
        current += self.unlexer.OB()
        current += self.unlexer.SF()
        current += self.create_node(UnlexerRule(src='id'))
        current += self.unlexer.SF()
        current += self.unlexer.COLLON()
        current += self.unlexer.SF()
        current += self.guid()
        current += self.unlexer.SF()
        current += self.unlexer.COMMA()
        current += self.unlexer.SF()
        current += self.create_node(UnlexerRule(src='name'))
        current += self.unlexer.SF()
        current += self.unlexer.COLLON()
        current += self.unlexer.SF()
        current += self.string()
        current += self.unlexer.SF()
        current += self.unlexer.COMMA()
        current += self.unlexer.SF()
        current += self.create_node(UnlexerRule(src='releaseDate'))
        current += self.unlexer.SF()
        current += self.unlexer.COLLON()
        current += self.releaseDate()
        current += self.unlexer.COMMA()
        current += self.unlexer.SF()
        current += self.create_node(UnlexerRule(src='manufacturer'))
        current += self.unlexer.SF()
        current += self.unlexer.COLLON()
        current += self.manufacturer()
        current += self.unlexer.CB()
        current += self.create_node(UnlexerRule(src='"'))
        return current
    data.min_depth = 4

    @depthcontrol
    def manufacturer(self):
        current = self.create_node(UnparserRule(name='manufacturer'))
        current += self.unlexer.OB()
        current += self.unlexer.SF()
        current += self.create_node(UnlexerRule(src='name'))
        current += self.unlexer.SF()
        current += self.unlexer.COLLON()
        current += self.unlexer.SF()
        current += self.string()
        current += self.unlexer.SF()
        current += self.unlexer.COMMA()
        current += self.unlexer.SF()
        current += self.create_node(UnlexerRule(src='homePage'))
        current += self.unlexer.SF()
        current += self.unlexer.COLLON()
        current += self.unlexer.SF()
        current += self.homepage()
        current += self.unlexer.SF()
        current += self.unlexer.COMMA()
        current += self.unlexer.SF()
        current += self.create_node(UnlexerRule(src='phone'))
        current += self.unlexer.SF()
        current += self.unlexer.COLLON()
        current += self.unlexer.SF()
        current += self.phone()
        current += self.unlexer.SF()
        current += self.unlexer.CB()
        return current
    manufacturer.min_depth = 3

    @depthcontrol
    def releaseDate(self):
        current = self.create_node(UnparserRule(name='releaseDate'))
        current += self.unlexer.OB()
        current += self.date()
        current += self.unlexer.CB()
        return current
    releaseDate.min_depth = 3

    @depthcontrol
    def addInventoryItem(self):
        current = self.create_node(UnparserRule(name='addInventoryItem'))
        current += self.create_node(UnlexerRule(src='curl -X POST "https://virtserver.swaggerhub.com/dmusy/2048_tracking/1.0.0/inventory" -H  "accept: application/json" -H  "Content-Type: application/json" -d '))
        current += self.data()
        return current
    addInventoryItem.min_depth = 5

    @depthcontrol
    def searchInventory(self):
        current = self.create_node(UnparserRule(name='searchInventory'))
        current += self.create_node(UnlexerRule(src='curl -X GET "https://virtserver.swaggerhub.com/dmusy/2048_tracking/1.0.0/inventory?searchString='))
        current += self.string()
        current += self.create_node(UnlexerRule(src='&skip='))
        current += self.integer()
        current += self.create_node(UnlexerRule(src='&limit='))
        current += self.integer()
        current += self.create_node(UnlexerRule(src='" -H  "accept: application/json"'))
        return current
    searchInventory.min_depth = 2

    default_rule = start

